// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhrX3_on1SxzVd6QlOSYcTxBUVivQfmaY',
    appId: '1:433810814971:web:8a619db7cb98007ea07d5e',
    messagingSenderId: '433810814971',
    projectId: 'zytronic-whatsapp-task',
    authDomain: 'zytronic-whatsapp-task.firebaseapp.com',
    storageBucket: 'zytronic-whatsapp-task.firebasestorage.app',
    measurementId: 'G-2W8Q33V4XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zuewK8eXeWVx1_zc9I-u68xQzQYmmY0',
    appId: '1:433810814971:android:b8081cd12f8f925ba07d5e',
    messagingSenderId: '433810814971',
    projectId: 'zytronic-whatsapp-task',
    storageBucket: 'zytronic-whatsapp-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChQEo3qx9A-_Vnc00xvbgbmvOn_-Fh24',
    appId: '1:433810814971:ios:349da224603601cfa07d5e',
    messagingSenderId: '433810814971',
    projectId: 'zytronic-whatsapp-task',
    storageBucket: 'zytronic-whatsapp-task.firebasestorage.app',
    iosBundleId: 'com.example.zytronicWhatsappTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDChQEo3qx9A-_Vnc00xvbgbmvOn_-Fh24',
    appId: '1:433810814971:ios:349da224603601cfa07d5e',
    messagingSenderId: '433810814971',
    projectId: 'zytronic-whatsapp-task',
    storageBucket: 'zytronic-whatsapp-task.firebasestorage.app',
    iosBundleId: 'com.example.zytronicWhatsappTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhrX3_on1SxzVd6QlOSYcTxBUVivQfmaY',
    appId: '1:433810814971:web:da076326826b7071a07d5e',
    messagingSenderId: '433810814971',
    projectId: 'zytronic-whatsapp-task',
    authDomain: 'zytronic-whatsapp-task.firebaseapp.com',
    storageBucket: 'zytronic-whatsapp-task.firebasestorage.app',
    measurementId: 'G-7Z8SRLJ5D5',
  );
}
